CREATE TABLE `pay2cash` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`account_id` INT(11) NOT NULL,
	`donate` INT(11) NOT NULL,
	`status` ENUM('pending','complete') NOT NULL DEFAULT 'pending',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='cp1251_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;